# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: transfer.proto

import sys
_b=sys.version_info[0]<3 and (lambda x:x) or (lambda x:x.encode('latin1'))
from google.protobuf import descriptor as _descriptor
from google.protobuf import message as _message
from google.protobuf import reflection as _reflection
from google.protobuf import symbol_database as _symbol_database
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()




DESCRIPTOR = _descriptor.FileDescriptor(
  name='transfer.proto',
  package='network',
  syntax='proto3',
  serialized_options=None,
  serialized_pb=_b('\n\x0etransfer.proto\x12\x07network\"\x18\n\x05\x45mpty\x12\x0f\n\x07\x63ontent\x18\x01 \x01(\t\"&\n\x05Party\x12\x0f\n\x07partyId\x18\x01 \x01(\t\x12\x0c\n\x04name\x18\x02 \x01(\t\"\x15\n\x05\x42ytes\x12\x0c\n\x04\x64\x61ta\x18\x01 \x01(\x0c\"T\n\x0bRequestMeta\x12\x0b\n\x03tag\x18\x01 \x01(\t\x12\x1b\n\x03src\x18\x02 \x01(\x0b\x32\x0e.network.Party\x12\x1b\n\x03\x64st\x18\x03 \x01(\x0b\x32\x0e.network.Party\"\x82\x01\n\x07Message\x12\x1f\n\x05\x65mpty\x18\x01 \x01(\x0b\x32\x0e.network.EmptyH\x00\x12\x1f\n\x05\x62ytes\x18\x02 \x01(\x0b\x32\x0e.network.BytesH\x00\x12*\n\x0crequest_meta\x18\x03 \x01(\x0b\x32\x14.network.RequestMetaB\t\n\x07\x63ontent2\xa0\x01\n\x0eTransferServer\x12(\n\x04recv\x12\x10.network.Message\x1a\x0e.network.Empty\x12(\n\x04send\x12\x10.network.Message\x1a\x0e.network.Empty\x12:\n\x10get_local_server\x12\x14.network.RequestMeta\x1a\x10.network.Messageb\x06proto3')
)




_EMPTY = _descriptor.Descriptor(
  name='Empty',
  full_name='network.Empty',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  fields=[
    _descriptor.FieldDescriptor(
      name='content', full_name='network.Empty.content', index=0,
      number=1, type=9, cpp_type=9, label=1,
      has_default_value=False, default_value=_b("").decode('utf-8'),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  serialized_options=None,
  is_extendable=False,
  syntax='proto3',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=27,
  serialized_end=51,
)


_PARTY = _descriptor.Descriptor(
  name='Party',
  full_name='network.Party',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  fields=[
    _descriptor.FieldDescriptor(
      name='partyId', full_name='network.Party.partyId', index=0,
      number=1, type=9, cpp_type=9, label=1,
      has_default_value=False, default_value=_b("").decode('utf-8'),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
    _descriptor.FieldDescriptor(
      name='name', full_name='network.Party.name', index=1,
      number=2, type=9, cpp_type=9, label=1,
      has_default_value=False, default_value=_b("").decode('utf-8'),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  serialized_options=None,
  is_extendable=False,
  syntax='proto3',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=53,
  serialized_end=91,
)


_BYTES = _descriptor.Descriptor(
  name='Bytes',
  full_name='network.Bytes',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  fields=[
    _descriptor.FieldDescriptor(
      name='data', full_name='network.Bytes.data', index=0,
      number=1, type=12, cpp_type=9, label=1,
      has_default_value=False, default_value=_b(""),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  serialized_options=None,
  is_extendable=False,
  syntax='proto3',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=93,
  serialized_end=114,
)


_REQUESTMETA = _descriptor.Descriptor(
  name='RequestMeta',
  full_name='network.RequestMeta',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  fields=[
    _descriptor.FieldDescriptor(
      name='tag', full_name='network.RequestMeta.tag', index=0,
      number=1, type=9, cpp_type=9, label=1,
      has_default_value=False, default_value=_b("").decode('utf-8'),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
    _descriptor.FieldDescriptor(
      name='src', full_name='network.RequestMeta.src', index=1,
      number=2, type=11, cpp_type=10, label=1,
      has_default_value=False, default_value=None,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
    _descriptor.FieldDescriptor(
      name='dst', full_name='network.RequestMeta.dst', index=2,
      number=3, type=11, cpp_type=10, label=1,
      has_default_value=False, default_value=None,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  serialized_options=None,
  is_extendable=False,
  syntax='proto3',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=116,
  serialized_end=200,
)


_MESSAGE = _descriptor.Descriptor(
  name='Message',
  full_name='network.Message',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  fields=[
    _descriptor.FieldDescriptor(
      name='empty', full_name='network.Message.empty', index=0,
      number=1, type=11, cpp_type=10, label=1,
      has_default_value=False, default_value=None,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
    _descriptor.FieldDescriptor(
      name='bytes', full_name='network.Message.bytes', index=1,
      number=2, type=11, cpp_type=10, label=1,
      has_default_value=False, default_value=None,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
    _descriptor.FieldDescriptor(
      name='request_meta', full_name='network.Message.request_meta', index=2,
      number=3, type=11, cpp_type=10, label=1,
      has_default_value=False, default_value=None,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  serialized_options=None,
  is_extendable=False,
  syntax='proto3',
  extension_ranges=[],
  oneofs=[
    _descriptor.OneofDescriptor(
      name='content', full_name='network.Message.content',
      index=0, containing_type=None, fields=[]),
  ],
  serialized_start=203,
  serialized_end=333,
)

_REQUESTMETA.fields_by_name['src'].message_type = _PARTY
_REQUESTMETA.fields_by_name['dst'].message_type = _PARTY
_MESSAGE.fields_by_name['empty'].message_type = _EMPTY
_MESSAGE.fields_by_name['bytes'].message_type = _BYTES
_MESSAGE.fields_by_name['request_meta'].message_type = _REQUESTMETA
_MESSAGE.oneofs_by_name['content'].fields.append(
  _MESSAGE.fields_by_name['empty'])
_MESSAGE.fields_by_name['empty'].containing_oneof = _MESSAGE.oneofs_by_name['content']
_MESSAGE.oneofs_by_name['content'].fields.append(
  _MESSAGE.fields_by_name['bytes'])
_MESSAGE.fields_by_name['bytes'].containing_oneof = _MESSAGE.oneofs_by_name['content']
DESCRIPTOR.message_types_by_name['Empty'] = _EMPTY
DESCRIPTOR.message_types_by_name['Party'] = _PARTY
DESCRIPTOR.message_types_by_name['Bytes'] = _BYTES
DESCRIPTOR.message_types_by_name['RequestMeta'] = _REQUESTMETA
DESCRIPTOR.message_types_by_name['Message'] = _MESSAGE
_sym_db.RegisterFileDescriptor(DESCRIPTOR)

Empty = _reflection.GeneratedProtocolMessageType('Empty', (_message.Message,), {
  'DESCRIPTOR' : _EMPTY,
  '__module__' : 'transfer_pb2'
  # @@protoc_insertion_point(class_scope:network.Empty)
  })
_sym_db.RegisterMessage(Empty)

Party = _reflection.GeneratedProtocolMessageType('Party', (_message.Message,), {
  'DESCRIPTOR' : _PARTY,
  '__module__' : 'transfer_pb2'
  # @@protoc_insertion_point(class_scope:network.Party)
  })
_sym_db.RegisterMessage(Party)

Bytes = _reflection.GeneratedProtocolMessageType('Bytes', (_message.Message,), {
  'DESCRIPTOR' : _BYTES,
  '__module__' : 'transfer_pb2'
  # @@protoc_insertion_point(class_scope:network.Bytes)
  })
_sym_db.RegisterMessage(Bytes)

RequestMeta = _reflection.GeneratedProtocolMessageType('RequestMeta', (_message.Message,), {
  'DESCRIPTOR' : _REQUESTMETA,
  '__module__' : 'transfer_pb2'
  # @@protoc_insertion_point(class_scope:network.RequestMeta)
  })
_sym_db.RegisterMessage(RequestMeta)

Message = _reflection.GeneratedProtocolMessageType('Message', (_message.Message,), {
  'DESCRIPTOR' : _MESSAGE,
  '__module__' : 'transfer_pb2'
  # @@protoc_insertion_point(class_scope:network.Message)
  })
_sym_db.RegisterMessage(Message)



_TRANSFERSERVER = _descriptor.ServiceDescriptor(
  name='TransferServer',
  full_name='network.TransferServer',
  file=DESCRIPTOR,
  index=0,
  serialized_options=None,
  serialized_start=336,
  serialized_end=496,
  methods=[
  _descriptor.MethodDescriptor(
    name='recv',
    full_name='network.TransferServer.recv',
    index=0,
    containing_service=None,
    input_type=_MESSAGE,
    output_type=_EMPTY,
    serialized_options=None,
  ),
  _descriptor.MethodDescriptor(
    name='send',
    full_name='network.TransferServer.send',
    index=1,
    containing_service=None,
    input_type=_MESSAGE,
    output_type=_EMPTY,
    serialized_options=None,
  ),
  _descriptor.MethodDescriptor(
    name='get_local_server',
    full_name='network.TransferServer.get_local_server',
    index=2,
    containing_service=None,
    input_type=_REQUESTMETA,
    output_type=_MESSAGE,
    serialized_options=None,
  ),
])
_sym_db.RegisterServiceDescriptor(_TRANSFERSERVER)

DESCRIPTOR.services_by_name['TransferServer'] = _TRANSFERSERVER

# @@protoc_insertion_point(module_scope)
